import type { CSSProperties } from 'react';

/**
 * Shared inline style objects for the driver-verification admin pages,
 * matching the plain-inline-style convention already used by login/page.tsx
 * and app/page.tsx (no CSS-in-JS library or Tailwind is set up in this app).
 */
export const styles = {
  page: {
    maxWidth: 1000,
    margin: '0 auto',
    padding: '32px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
  },
  title: { margin: 0, fontSize: 26, color: 'var(--color-text-primary)' },
  backLink: { fontSize: 14, fontWeight: 600 },
  filterForm: {
    display: 'flex',
    gap: 12,
    flexWrap: 'wrap',
    alignItems: 'flex-end',
  },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: { fontSize: 13, fontWeight: 600, color: 'var(--color-text-secondary)' },
  input: {
    minHeight: 40,
    padding: '0 10px',
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    fontSize: 14,
    minWidth: 200,
  },
  select: {
    minHeight: 40,
    padding: '0 10px',
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    fontSize: 14,
    background: '#fff',
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    textAlign: 'left',
    padding: '10px 12px',
    fontSize: 13,
    color: 'var(--color-text-secondary)',
    borderBottom: '1px solid var(--color-border)',
  },
  td: {
    padding: '12px',
    fontSize: 14,
    borderBottom: '1px solid var(--color-border)',
    verticalAlign: 'middle',
  },
  rowLink: { color: 'var(--color-text-primary)', textDecoration: 'none', fontWeight: 600 },
  emptyState: { padding: '32px 12px', textAlign: 'center', color: 'var(--color-text-secondary)' },
  pagination: { display: 'flex', gap: 8, alignItems: 'center', fontSize: 14 },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: 20,
    borderRadius: 12,
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface)',
  },
  sectionTitle: { margin: 0, fontSize: 18, color: 'var(--color-text-primary)' },
  definitionList: { display: 'grid', gridTemplateColumns: '200px 1fr', rowGap: 8, columnGap: 12 },
  dt: { fontSize: 13, color: 'var(--color-text-secondary)', fontWeight: 600 },
  dd: { fontSize: 14, color: 'var(--color-text-primary)', margin: 0 },
  buttonPrimary: {
    minHeight: 40,
    padding: '0 16px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--color-primary)',
    color: '#fff',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
  },
  buttonSecondary: {
    minHeight: 40,
    padding: '0 16px',
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'transparent',
    color: 'var(--color-text-primary)',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  buttonDanger: {
    minHeight: 40,
    padding: '0 16px',
    borderRadius: 8,
    border: '1px solid var(--color-error)',
    background: 'transparent',
    color: 'var(--color-error)',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
  },
  buttonRow: { display: 'flex', gap: 10, flexWrap: 'wrap' },
  errorText: {
    margin: 0,
    padding: '8px 12px',
    borderRadius: 8,
    background: '#fdecea',
    color: 'var(--color-error)',
    fontSize: 14,
  },
  missingList: { margin: '4px 0 0', paddingLeft: 20, fontSize: 13, color: 'var(--color-error)' },
  dialog: {
    borderRadius: 12,
    border: '1px solid var(--color-border)',
    padding: 0,
    maxWidth: 440,
    width: '90vw',
  },
  dialogBody: { display: 'flex', flexDirection: 'column', gap: 12, padding: 20 },
  textarea: {
    minHeight: 96,
    padding: 10,
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    fontSize: 14,
    fontFamily: 'inherit',
    resize: 'vertical',
  },
  tabList: { display: 'flex', gap: 4, borderBottom: '1px solid var(--color-border)' },
  tab: {
    minHeight: 44,
    padding: '0 16px',
    background: 'transparent',
    border: 'none',
    borderBottom: '2px solid transparent',
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--color-text-secondary)',
    cursor: 'pointer',
  },
  tabActive: { color: 'var(--color-primary)', borderBottom: '2px solid var(--color-primary)' },
  documentRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    padding: '12px 0',
    borderBottom: '1px solid var(--color-border)',
  },
  historyItem: {
    padding: '10px 0',
    borderBottom: '1px solid var(--color-border)',
    fontSize: 14,
  },
} satisfies Record<string, CSSProperties>;

export const STATUS_LABEL: Record<string, string> = {
  NOT_STARTED: 'Not started',
  IN_PROGRESS: 'In progress',
  SUBMITTED: 'Submitted',
  UNDER_REVIEW: 'Under review',
  VERIFIED: 'Verified',
  REJECTED: 'Rejected',
  SUSPENDED: 'Suspended',
  PENDING: 'Pending',
  APPROVED: 'Approved',
  EXPIRED: 'Expired',
};

const STATUS_COLOR: Record<string, string> = {
  NOT_STARTED: 'var(--color-text-secondary)',
  IN_PROGRESS: 'var(--color-warning)',
  SUBMITTED: 'var(--color-warning)',
  UNDER_REVIEW: 'var(--color-warning)',
  VERIFIED: 'var(--color-success)',
  APPROVED: 'var(--color-success)',
  REJECTED: 'var(--color-error)',
  SUSPENDED: 'var(--color-error)',
  EXPIRED: 'var(--color-error)',
  PENDING: 'var(--color-warning)',
};

export function statusBadgeStyle(status: string): CSSProperties {
  const color = STATUS_COLOR[status] ?? 'var(--color-text-secondary)';
  return {
    display: 'inline-block',
    padding: '2px 10px',
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 700,
    color,
    border: `1px solid ${color}`,
  };
}
